
COMPAREBUT="השווה וחסוך💰"
BOREDBUT="🥱משועמם בתור?"
ABOUTBUT="👾אודות הבוט"
UPDAETBUT="עודכן לאחרונה ב:"
CHANNELBUT="ערוץ מבצעים💸"
UNDERSTOODBUT="👌הבנתי!"
DO_NOT_TYPEBUT="🤦🏼‍♀️!!!אין לי כח להקליד"
BACKBUT="🔙חזור"
MY_LISTBUT="הרשימה שלי 📝"
ADD_TO_LISTBUT="הוסף לרשימה ✏️"
DEL_FROM_LISTBUT="מחק מהרשימה ❌"
DEL_ALL_LISTBUT="מחק את כל הרשימה✖️"
SHOW_ALLBUT="הצג סהכ 📊"
LISTBUT="רשימת קניות📜"
VIDEO_BUT="לא הבנתי 📹"
BRANCHES_BUT="בחירת רשתות וסניפים 🎯"
OSHERAD_BUT="אושר עד 🔵"
RAMILEVI_BUT="רמי לוי 🔴"
YOHANANOF_BUT="יוחננוף 🟡"
ADD_BRANCHE_BUT="הוסף סניף להשוואה 🏬"
DEL_BRANCHE_BUT="הסר סניף להשוואה ❌"
ALL_MY_BRANCHE_BUT="הסניפים שלי 📈"

MY_USER_NAME=" @yonilabell"
HELLO="שלום "
TO_COMPANS="כדי להשוות מחיר מוצר אנא הכנס מזהה מוצר שנמצא מתחת לברקוד"
TO_COMPANS+="\n"
TO_COMPANS+=" או הכנס שם מוצר ובחר מהרשימה "
BOT_DEVANS="הבוט בפיתוח ע'י"
WAIT_ANS="כבר שולח סרטון, כמה שניות"
UNDERSTOODANS="בסדר גמור, מובן לחלוטין ! יש לי פתרון לעצלנים כמוני, פשוט צלם את הברקוד עם הספרות מתחתיו ושלח את התמונה לבוט הזה: @qrcrbot. ושלח לי את התוצאה "
BACKANS="🔙חזרתי"
CHANANS="https://t.me/salesChan"
TYPEANS="הכנס מזהה מוצר"
NOT_FOUNDANS='לא הבנתי את בקשתך'
BRANCHES_ANS="בחר רשת"
ADD_DEL_ANS='הוסף או מחק'
DONE_ANS='בוצע!'
ADD_COMANDREP="אוקי! מה להוסיף"
DEL_COMANDREP="אוקי! מה למחוק"
SELECT_BRANCH_REP='בחר סניף'
NOTE_REP="*מציג רק את הרשתות שבהן קיימים כל המוצרים ברשימה שלך"
NO_STORE_REP="לא קיימים סניפים להשוואה! אנא הוסף סניפים."
RamiLevi='רמי לוי'
osherad='אושר עד'
yohananof='יוחננוף'
